image: op-gitlab.howest.be:4567/docker-registry/html-validator

stages:
  - QA
  - deploy

validateHTML:
  stage: QA
  script:
    - npm install
    - npm run validate
    
deploy:
  image: debian:latest
  before_script:
    - echo "we don't need gradle or maven anymore"
  stage: deploy
  only:
    - master
  except:
    changes:
      - documents/**/*
  script:
    - apt update -y && apt install -y software-properties-common
    - 'which ssh-agent || apt install -y openssh-client cowsay'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 172.18.18.201 >> ~/.ssh/known_hosts
    - scp -qr ./src/* gitlab-runner@172.18.18.201:"/var/www/html/2019-2020/alhambra-${CI_PROJECT_NAMESPACE:(-2)}/"
  environment: production

